const SET_ONLY_SHOW_2_PRODUCTS = 'boilerplatetrieuth/ProductsList/SET_ONLY_SHOW_2_PRODUCTS';
const SET_ONLY_SHOW_2_PRODUCTS_START = 'boilerplatetrieuth/ProductsList/SET_ONLY_SHOW_2_PRODUCTS_START';
const SET_ONLY_SHOW_2_PRODUCTS_SUCCESS = 'boilerplatetrieuth/ProductsList/SET_ONLY_SHOW_2_PRODUCTS_SUCCESS';
const SET_ONLY_SHOW_2_PRODUCTS_ERROR = 'boilerplatetrieuth/ProductsList/SET_ONLY_SHOW_2_PRODUCTS_ERROR';

export {
    SET_ONLY_SHOW_2_PRODUCTS,
    SET_ONLY_SHOW_2_PRODUCTS_START,
    SET_ONLY_SHOW_2_PRODUCTS_SUCCESS,
    SET_ONLY_SHOW_2_PRODUCTS_ERROR
}